import { screen, within } from "@testing-library/react";
import { beforeEach, describe, expect, it, vi } from "vitest";
import { metadata } from "../../data/fixtures";
import type { WhatChangedView } from "../../data/schemas";
import { DEFAULT_SITE_META, type SiteMeta } from "../../layout/siteMeta";
import { renderRoute } from "../../test/renderRoute";
import { parseBulletin } from "./bulletinMarkdown";

const views = vi.hoisted(() => ({ current: {} as Record<string, unknown> }));

vi.mock("../../data/useView", () => ({
  useView: (name: string) => views.current[name] ?? { status: "loading", data: undefined, error: undefined },
}));

const BULLETIN = [
  "## Open edX Repo Health Weekly Bulletin",
  "Generated: 2026-10-02 13:29 UTC",
  "",
  "### Newly failing checks",
  "- openedx/a: has_readme",
  "",
  "### Newly passing checks",
  "- None",
  "",
  "Dashboard: https://openedx.ossvitals.org",
  "Generated by Open edX Repository Health Dashboard",
].join("\n");

function whatChangedFixture(overrides: Partial<WhatChangedView> = {}): WhatChangedView {
  return {
    metadata: metadata("two most recent snapshots"),
    snapshots: 5,
    latest: "2026-10-02T06:00:00+00:00",
    previous: "2026-10-01T06:00:00+00:00",
    new_failures: [
      { repo_name: "openedx/b", check: "has_readme" },
      { repo_name: "openedx/a", check: "has_license" },
    ],
    new_passes: [{ repo_name: "openedx/c", check: "has_codeowners" }],
    bulletin: BULLETIN,
    ...overrides,
  };
}

function setView(view: WhatChangedView) {
  views.current = { what_changed: { status: "ready", data: view, error: undefined } };
}

function withBulletinExport(enabled: boolean): SiteMeta {
  return { ...DEFAULT_SITE_META, featureFlags: { ...DEFAULT_SITE_META.featureFlags, enableWeeklyBulletinExport: enabled } };
}

beforeEach(() => setView(whatChangedFixture()));

describe("What Changed page", () => {
  it("renders the caption and both change tables with repo links", async () => {
    renderRoute("/what_changed");

    expect(await screen.findByRole("heading", { level: 1, name: "What Changed" })).toBeInTheDocument();
    expect(document.title).toBe("What Changed · Open edX Repo Health");
    expect(
      screen.getByText(
        "Comparing the two most recent snapshots: 2026-10-01T06:00:00+00:00 → 2026-10-02T06:00:00+00:00 (UTC). 5 snapshots available.",
      ),
    ).toBeInTheDocument();

    const failing = screen.getByRole("table", { name: "Newly failing checks" });
    expect(within(failing).getByRole("link", { name: "openedx/a" })).toHaveAttribute("href", "/repo_detail?repo=openedx%2Fa");
    expect(within(failing).getByText("has_readme")).toBeInTheDocument();

    const passing = screen.getByRole("table", { name: "Newly passing checks" });
    expect(within(passing).getByRole("link", { name: "openedx/c" })).toHaveAttribute("href", "/repo_detail?repo=openedx%2Fc");
    expect(within(passing).getByText("has_codeowners")).toBeInTheDocument();

    expect(screen.getByRole("button", { name: "Copy link to this view" })).toBeInTheDocument();
  });

  it("shows the empty states when nothing changed", async () => {
    setView(whatChangedFixture({ new_failures: [], new_passes: [] }));
    renderRoute("/what_changed");

    const regressed = await screen.findByText("No newly failing checks.");
    expect(regressed.closest(".empty-state")).toHaveClass("empty-state--good");
    expect(screen.getByText("Nothing regressed between these two snapshots.")).toBeInTheDocument();

    const fixed = screen.getByText("No newly passing checks.");
    expect(fixed.closest(".empty-state")).toHaveClass("empty-state--info");
    expect(screen.getByText("Nothing was fixed between these two snapshots either.")).toBeInTheDocument();
    expect(screen.queryByRole("table")).not.toBeInTheDocument();
  });

  it("warns when there is not enough history to compare", async () => {
    setView(
      whatChangedFixture({ snapshots: 1, latest: undefined, previous: undefined, new_failures: [], new_passes: [], bulletin: undefined }),
    );
    renderRoute("/what_changed");

    const title = await screen.findByText("Not enough history to compare.");
    expect(title.closest(".empty-state")).toHaveClass("empty-state--warn");
    expect(
      screen.getByText(
        "At least two snapshots are needed. The accumulated history file is published by the upstream pipeline; if this persists, that file is missing or holds only one entry.",
      ),
    ).toBeInTheDocument();
    expect(screen.queryByRole("heading", { name: "Newly failing checks" })).not.toBeInTheDocument();
    expect(screen.getByRole("button", { name: "Copy link to this view" })).toBeInTheDocument();
  });

  it("renders the bulletin, its markdown source and the download", async () => {
    renderRoute("/what_changed");

    const section = (await screen.findByRole("heading", { level: 2, name: "Bulletin" })).closest("section");
    expect(section).not.toBeNull();
    const bulletin = within(section as HTMLElement);
    expect(bulletin.getByRole("heading", { level: 3, name: "Open edX Repo Health Weekly Bulletin" })).toBeInTheDocument();
    expect(bulletin.getByRole("heading", { level: 4, name: "Newly failing checks" })).toBeInTheDocument();
    expect(bulletin.getByText("openedx/a: has_readme", { selector: "li" })).toBeInTheDocument();
    expect(bulletin.getByText("Dashboard: https://openedx.ossvitals.org", { selector: "p" })).toBeInTheDocument();
    expect(bulletin.getByText("Copy markdown source", { selector: "summary" })).toBeInTheDocument();
    expect(bulletin.getByLabelText("Bulletin markdown")).toHaveValue(BULLETIN);
    expect(bulletin.getByLabelText("Bulletin markdown")).toHaveAttribute("readonly");
    expect(bulletin.getByRole("button", { name: "Download bulletin" })).toBeInTheDocument();
  });

  it("hides the bulletin when the export flag is off", async () => {
    renderRoute("/what_changed", withBulletinExport(false));

    await screen.findByRole("table", { name: "Newly failing checks" });
    expect(screen.queryByRole("heading", { name: "Bulletin" })).not.toBeInTheDocument();
    expect(screen.queryByRole("button", { name: "Download bulletin" })).not.toBeInTheDocument();
  });

  it("hides the bulletin when the data has none", async () => {
    setView(whatChangedFixture({ bulletin: undefined }));
    renderRoute("/what_changed");

    await screen.findByRole("table", { name: "Newly failing checks" });
    expect(screen.queryByRole("heading", { name: "Bulletin" })).not.toBeInTheDocument();
  });

  it("shows the load error", async () => {
    views.current = { what_changed: { status: "error", data: undefined, error: new Error("what_changed.json: not found") } };
    renderRoute("/what_changed");

    expect(await screen.findByRole("alert")).toHaveTextContent("what_changed.json: not found");
  });
});

describe("parseBulletin", () => {
  it("turns headings, list items and plain lines into blocks", () => {
    expect(parseBulletin(BULLETIN)).toEqual([
      { kind: "heading", level: 2, text: "Open edX Repo Health Weekly Bulletin" },
      { kind: "paragraph", text: "Generated: 2026-10-02 13:29 UTC" },
      { kind: "heading", level: 3, text: "Newly failing checks" },
      { kind: "list", items: ["openedx/a: has_readme"] },
      { kind: "heading", level: 3, text: "Newly passing checks" },
      { kind: "list", items: ["None"] },
      { kind: "paragraph", text: "Dashboard: https://openedx.ossvitals.org" },
      { kind: "paragraph", text: "Generated by Open edX Repository Health Dashboard" },
    ]);
  });

  it("groups consecutive list items into one list", () => {
    expect(parseBulletin("### Checks\n- a: x\n- b: y\r\n- c: z")).toEqual([
      { kind: "heading", level: 3, text: "Checks" },
      { kind: "list", items: ["a: x", "b: y", "c: z"] },
    ]);
  });

  it("returns no blocks for empty input", () => {
    expect(parseBulletin("")).toEqual([]);
    expect(parseBulletin("\n\n")).toEqual([]);
  });
});
